### ISSUE TITLE
I am unable to compile, Compilation error: 'BASE64' has not been declared

### ISSUE THREAD

**Issue by honeykethan** [tendai98/ESP8266-CAN#1]
I was very excited to find this work on git hub which was very much required for our student vehicle which we are designing at our university, I am facing an issue with compiling it, It seems the problem is in my system or I am using a different library. Please Help!!

I have the BASE64 library downloaded from this repository: https://github.com/Densaugeo/base64_arduino

Error while compiling: 
In file included from C:\Users\honey\Downloads\ESP8266-CAN-main (1)\ESP8266-CAN-main\ESP8266-CAN\ESP8266-CAN.ino:3:
C:\Users\honey\Downloads\ESP8266-CAN-main (1)\ESP8266-CAN-main\ESP8266-CAN\server.h: In function 'void canWrite()':
C:\Users\honey\Downloads\ESP8266-CAN-main (1)\ESP8266-CAN-main\ESP8266-CAN\server.h:41:23: error: 'BASE64' has not been declared
   41 |     uint8_t frameData[BASE64::decodeLength(ingressBuffer)];
      |                       ^~~~~~
C:\Users\honey\Downloads\ESP8266-CAN-main (1)\ESP8266-CAN-main\ESP8266-CAN\server.h:42:5: error: 'BASE64' has not been declared
   42 |     BASE64::decode(ingressBuffer, frameData);
      |     ^~~~~~
C:\Users\honey\Downloads\ESP8266-CAN-main (1)\ESP8266-CAN-main\ESP8266-CAN\server.h:42:35: error: 'frameData' was not declared in this scope
   42 |     BASE64::decode(ingressBuffer, frameData);
      |                                   ^~~~~~~~~
C:\Users\honey\Downloads\ESP8266-CAN-main (1)\ESP8266-CAN-main\ESP8266-CAN\server.h: In function 'void canRead()':
C:\Users\honey\Downloads\ESP8266-CAN-main (1)\ESP8266-CAN-main\ESP8266-CAN\server.h:54:16: error: 'BASE64' has not been declared
   54 |       char b64[BASE64::encodeLength(MAX_FRAME_LEN)];
      |                ^~~~~~
C:\Users\honey\Downloads\ESP8266-CAN-main (1)\ESP8266-CAN-main\ESP8266-CAN\server.h:55:7: error: 'BASE64' has not been declared
   55 |       BASE64::encode((const uint8_t*) &canMsg, MAX_FRAME_LEN, b64);
      |       ^~~~~~
C:\Users\honey\Downloads\ESP8266-CAN-main (1)\ESP8266-CAN-main\ESP8266-CAN\server.h:55:63: error: 'b64' was not declared in this scope; did you mean 'u64'?
   55 |       BASE64::encode((const uint8_t*) &canMsg, MAX_FRAME_LEN, b64);
      |                                                               ^~~
      |                                                               u64
In file included from C:\Users\honey\Downloads\ESP8266-CAN-main (1)\ESP8266-CAN-main\ESP8266-CAN\ESP8266-CAN.ino:1:
C:\Users\honey\Downloads\ESP8266-CAN-main (1)\ESP8266-CAN-main\ESP8266-CAN\ESP8266-CAN.ino: In function 'void setup()':
C:\Users\honey\Downloads\ESP8266-CAN-main (1)\ESP8266-CAN-main\ESP8266-CAN\const.h:1:17: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
    1 | #define AP_SSID "iCAN-1"
      |                 ^~~~~~~~
C:\Users\honey\Downloads\ESP8266-CAN-main (1)\ESP8266-CAN-main\ESP8266-CAN\ESP8266-CAN.ino:17:15: note: in expansion of macro 'AP_SSID'
   17 |   startWiFiAP(AP_SSID, AP_PASS);
      |               ^~~~~~~
C:\Users\honey\Downloads\ESP8266-CAN-main (1)\ESP8266-CAN-main\ESP8266-CAN\const.h:2:17: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
    2 | #define AP_PASS "canbus1234"
      |                 ^~~~~~~~~~~~
C:\Users\honey\Downloads\ESP8266-CAN-main (1)\ESP8266-CAN-main\ESP8266-CAN\ESP8266-CAN.ino:17:24: note: in expansion of macro 'AP_PASS'
   17 |   startWiFiAP(AP_SSID, AP_PASS);
      |                        ^~~~~~~

exit status 1

Compilation error: 'BASE64' has not been declared

**Comment by tendai98** [comment]
Hi , hope you are doing well. Did you try to compile the code in
Aruduino IDE and also did you use the NodeMCU board in the settings because
the project was done using Arduino IDE and targeting the NodeMCU (ESP8266)
board, I will recompile it and give feedback to you especially on the
BASE64 library

**Comment by honeykethan** [comment]
Hi, Greetings of the day, I am good hope you are doing good, Thank you for your replay
I am compiling the code on Arduino IDE and targeting NodeMCU 1.0 (ESP12E module) which is ESP8266 board. Did also try targeting NodeMCU 0.9 (ESP12 module) to check if it works 
Looking forward for your replay and appreciate your support.

**Comment by tendai98** [comment]
So I have been having issues compiling the code with the new Arduino version. When I worked on the project, I was using Arduino 1.6 so now I am refactoring the code so that it works on the new Arduino version and I found the library for the base64 decode and encode operations

**Comment by honeykethan** [comment]
Could you please specify the source of the base64 library you have used, So that I can use the same which might solve the issue.

**Comment by tendai98** [comment]
Okay, let do that

**Comment by tendai98** [comment]
The code has compiled, I have have made some changes to it and added a custom base64.h file by taking the code from the base64 library because compiling it with the new Arduino IDE wasnt working until I made those changes. I am commiting the new update to my github

**Comment by honeykethan** [comment]
Thank you.

**Comment by tendai98** [comment]
This is the base64 code repository:  https://github.com/dojyorin/arduino_base64.git
This is the mcp2515 CAN controller repository: https://github.com/autowp/arduino-mcp2515.git

So these are the repos I used for the project

**Comment by tendai98** [comment]
All the best on your project

**Comment by tendai98** [comment]
Let me know if everything works out so that I can close the issue

**Comment by honeykethan** [comment]
I was able to compile the code and flash it on ESP8266, thanks for your support.

Now I want to receive the CAN msg on my Android so that I can work on interfacing it with our app, I am trying to run can_filter.py on my Android device by connecting it with the ESP8266 through Wi-Fi as you have shown When I try this It says 6 ECU detected which is correct as there are 6 CAN IDs, But it does not show the message instead keep flickering. Would appreciate your support if you could help me over-come this issue. 
![Screenshot_20240416-165503](https://github.com/tendai98/ESP8266-CAN/assets/38936455/b5dba2e1-9369-403d-870c-9a707d2e2d86)

**Comment by honeykethan** [comment]
I can receive the CAN msg on my Android device after trying the can_scan.py file. Once again Thank you very much for your support.

You can close the issue.

**Comment by honeykethan** [comment]
I also wanted to know if is it possible to send any CAN message from Android to CAN network through this code.

**Comment by tendai98** [comment]
Yes its possible, there is send HTTP route on the code that received a CAN packet from a client and then forwards it to the MCP2515, if you go in the "scripts"  folder in the project, there is a "can_write.sh" file which sends a CAN packet encoded in BASE64 to the device, the reason for first encoding the packet first in BASE64 is because I had issues sending binary data to he ESP8266 so for a client to send CAN data packets, first encode them to BASE64 and then send them via a URL pointing to the device with the NodeMCU and MCP2515. However I never really used the feature, I was mostly scanning the CAN bus but you can send CAN packets

**Comment by tendai98** [comment]
Also go in the utils folder, you should see Python scripts that fetch data from the device , it would help to understand some of the innerworkings

**Comment by honeykethan** [comment]
Understood, Thank you for the support, looks like have to explore more with the code on sending CAN messages through mobile.

**Comment by tendai98** [comment]
Sure thing, Just a tip, you can send the CAN messages through mobile, all you have to write some code that can send a HTTP GET Request with a CAN packet encoded in BASE64 by using the command in the URL in the can_write.sh file. its why I added http support to the project so that it could be integrated with any client, be it native-mobile, Powershell, bash , etc
