### ISSUE TITLE
Pin conections ESP8266 -> MPC2515

### ISSUE THREAD

**Issue by loomloom** [tendai98/ESP8266-CAN#2]
Hello,
Could you please list the correct pins for the correct connection between the esp8266 and the mcp2515?

Best Regards

**Comment by tendai98** [comment]
Sure thing, Sorry I forgot to add that to my README file

ESP8266 -   MCP2515
D2           ->    INT
D5           ->    SCK
D7           ->    SI (MOSI)
D6           ->    SO (MISO)
D8           ->    CS
GND        ->    GND
Vin           ->   VCC

**Comment by loomloom** [comment]
Thank you very much for your help.

**Comment by tendai98** [comment]
You are welcome. All the best
