### ISSUE TITLE
No logic level conversion?

### ISSUE THREAD

**Issue by alastaira** [tendai98/ESP8266-CAN#3]
Hi! According to the pin wiring, you're connecting the ESP8266 GPIO pins directly to the MCP2515, but connecting VCC to the (5V) VIn. 

So, when the MCP2515 pulls those lines HIGH, it's applying 5V direct to the ESP8266 GPIOs, which I would expect to damage them over any sort of extended use? 
I've always assumed a 3.3V <> 5V logic level convertor should be required?

**Comment by tendai98** [comment]
Hi, I used the NodeMCU and Wemos D1 mini for the project but if you want, you can use a logic level shifter to be safe , however I havent faced issues using the MCP2515 module directly with the ESP8266

**Comment by alastaira** [comment]
Thanks for the reply! That's interesting... I do use ESP32s a lot but using the built-in CAN controller and just a 3.3V transceiver (a SN65HVD230). And, for my 5V Arduinos it's straightforward to use the MCP2515/TJA1050 combination modules.
So it's really only the ESP8266 that I found more awkward...! 

I haven't found any documentation to state they are officially 5V tolerant on the GPIO pins, though there seem to be a lot of blog articles debating the subject... the specs seems to suggest 3.6V is the max, so I guess I'll stick some logic level convertors in.

**Comment by tendai98** [comment]
Yeah for me I have used them with 5V peripherals just fine, and there is a debate around them not being 5V-tolerant but I havent run into issues unlike the ESP32 which I know is 3.3V tolerant only
